steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - 'gs://rentomojo-ifaisalalam/gae_env.yaml'
      - '/workspace/backend/gae_env.yaml'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: '/workspace/backend'
