runtime: nodejs8

instance_class: F2

env_variables:
  APP_URL: https://api.rentomojo.ml/

includes:
  - gae_env.yaml

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
